CREATE TABLE DIRECTORY (
    id INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
    dir_name VARCHAR(30) DEFAULT NULL,
    rights SMALLINT DEFAULT 509,
    member_id INT DEFAULT NULL
);

create table MEMBER (
    id INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
    member_name VARCHAR(30) DEFAULT NULL,
    content BLOB NOT NULL DEFAULT NULL
);